'use client';

import React from 'react';
import LegalDocumentLayout from "@/components/common/LegalDocumentLayout";
import { Mail, Phone, Globe, MapPin } from "lucide-react";

export default function PrivacyPolicy() {
  return (
    <LegalDocumentLayout
      activeDoc="privacy"
      title="Privacy Policy"
      lastUpdated="Last updated: August 22, 2026"
    >
      <p>
        This Privacy Policy describes Our policies and procedures on the collection, use and disclosure of Your information when You use the Service and tells You about Your privacy rights and how the law protects You.
      </p>
      <p>
        We use Your Personal Data to provide and improve the Service. We collect, use, and disclose Your information as described in this Privacy Policy and, where required by applicable law, only where We have a valid legal basis to do so, including Your consent (where consent is required).
      </p>

      <h2>Interpretation and Definitions</h2>
      <h3>Interpretation</h3>
      <p>
        The words whose initial letters are capitalized have meanings defined under the following conditions. The following definitions shall have the same meaning regardless of whether they appear in singular or in plural.
      </p>

      <h3>Definitions</h3>
      <p>For the purposes of this Privacy Policy:</p>
      <ul>
        <li>
          <strong>Account</strong> means a unique account created for You to access Our Service or parts of Our Service.
        </li>
        <li>
          <strong>Affiliate</strong> means an entity that controls, is controlled by, or is under common control with a party, where &quot;control&quot; means ownership of 50% or more of the shares, equity interest or other securities entitled to vote for election of directors or other managing authority.
        </li>
        <li>
          <strong>Company</strong> (referred to as either &quot;the Company&quot;, &quot;We&quot;, &quot;Us&quot; or &quot;Our&quot; in this Privacy Policy) refers to <strong>hedena healthcare pvt ltd</strong>, IIT-Bhubaneswar Research Park, Samantapuri, Bhubaneswar – 751013.
        </li>
        <li>
          <strong>Cookies</strong> are small files that are placed on Your computer, mobile device or any other device by a website, containing the details of Your browsing history on that website, among its many uses.
        </li>
        <li>
          <strong>Country/State</strong> refers to: Orissa, India.
        </li>
        <li>
          <strong>Device</strong> means any device that can access the Service, such as a computer, a cell phone or a digital tablet.
        </li>
        <li>
          <strong>Personal Data</strong> (or &quot;Personal Information&quot;) is any information that relates to an identified or identifiable individual. We use &quot;Personal Data&quot; and &quot;Personal Information&quot; interchangeably unless a law uses a specific term.
        </li>
        <li>
          <strong>Service</strong> refers to the Website.
        </li>
        <li>
          <strong>Service Provider</strong> means any natural or legal person who processes the data on behalf of the Company. It refers to third-party companies or individuals employed by the Company to facilitate the Service, to provide the Service on behalf of the Company, to perform services related to the Service or to assist the Company in analyzing how the Service is used.
        </li>
        <li>
          <strong>Usage Data</strong> refers to data collected automatically, either generated by the use of the Service or from the Service infrastructure itself (for example, the duration of a page visit).
        </li>
        <li>
          <strong>User</strong> means any individual who accesses or uses the Service.
        </li>
        <li>
          <strong>Website</strong> refers to <strong>doxez</strong>, accessible from <a href="https://doxez.in" rel="external nofollow noopener" target="_blank">doxez.in</a>.
        </li>
        <li>
          <strong>You</strong> means the individual accessing or using the Service, or the company, or other legal entity on behalf of which such individual is accessing or using the Service, as applicable.
        </li>
      </ul>

      <h2>Collecting and Using Your Personal Information</h2>
      <h3>Types of Data Collected</h3>
      
      <h4>Personal Data</h4>
      <p>
        While using Our Service, We may ask You to provide Us with certain personally identifiable information that can be used to contact or identify You. Personally identifiable information may include, but is not limited to:
      </p>
      <ul>
        <li>Email address</li>
        <li>First name and last name</li>
        <li>Phone number</li>
        <li>Address, State, Province, ZIP/Postal code, City</li>
      </ul>

      <h4>Usage Data</h4>
      <p>Usage Data is collected automatically when using the Service.</p>
      <p>
        Usage Data may include information such as Your Device&apos;s Internet Protocol address (e.g. IP address), browser type, browser version, the pages of Our Service that You visit, the time and date of Your visit, the time spent on those pages, unique device identifiers and other diagnostic data.
      </p>
      <p>
        When You access the Service by or through a mobile device, We may collect certain information automatically, including, but not limited to, the type of mobile device You use, Your mobile device&apos;s unique ID, the IP address of Your mobile device, Your mobile operating system, the type of mobile Internet browser You use, unique device identifiers and other diagnostic data.
      </p>

      <h4>Tracking Technologies and Cookies</h4>
      <p>
        We use tracking technologies (such as cookies) to track the activity and to improve Our Service. The technologies We use may include:
      </p>
      <ul>
        <li>
          <strong>Cookies or Browser Cookies:</strong> A cookie is a small file placed on Your Device. You can instruct Your browser to refuse all Cookies or to indicate when a Cookie is being sent. However, if You do not accept Cookies, You may not be able to use some parts of Our Service.
        </li>
        <li>
          <strong>Web Beacons:</strong> Certain sections of Our Service may contain small electronic files known as web beacons (also referred to as clear gifs, pixel tags, and single-pixel gifs) that permit the Company, for example, to count users who have visited those pages and for other related website statistics.
        </li>
      </ul>

      <h2>Use of Your Personal Data</h2>
      <p>The Company may use Personal Data for the following purposes:</p>
      <ul>
        <li><strong>To provide and maintain Our Service</strong>, including to monitor the usage of Our Service.</li>
        <li><strong>To manage Your Account:</strong> to manage Your registration as a user of the Service.</li>
        <li><strong>For the performance of a contract:</strong> the development, compliance and undertaking of the purchase contract for the products, items or services You have purchased or of any other contract with Us through the Service.</li>
        <li><strong>To contact You:</strong> To contact You by email, telephone calls, SMS, or other equivalent forms of electronic communication regarding updates or informative communications related to functionalities, products, or contracted services.</li>
        <li><strong>To provide You</strong> with news, special offers, and general information about other goods, services and events which We offer that are similar to those that You have already purchased or inquired about.</li>
        <li><strong>To manage Your requests:</strong> To attend and manage Your requests to Us.</li>
        <li><strong>For business transfers:</strong> We may use Your Personal Data to evaluate or conduct a merger, divestiture, restructuring, reorganization, dissolution, or other sale or transfer of assets.</li>
        <li><strong>For other purposes:</strong> Such as data analysis, identifying usage trends, and evaluating and improving Our Service, products, marketing, and Your experience.</li>
      </ul>

      <div className="legal-note-box">
        <strong>Text Messages (SMS) Privacy Notice:</strong>
        <p style={{ margin: "6px 0 0" }}>
          You have the option to receive text (SMS) messages from Us. No mobile information will be shared with or sold to third parties or affiliates for marketing or promotional purposes. The phone numbers and consent records We collect for texting are never shared with anyone for any purpose, except the Service Providers that technically have to handle them to deliver the texts.
        </p>
      </div>

      <h2>Retention and Transfer of Your Personal Data</h2>
      <p>
        The Company will retain Your Personal Data only for as long as is necessary for the purposes set out in this Privacy Policy (for example, user accounts, support correspondence, and server analytics logs are retained for up to 24 months).
      </p>
      <p>
        Your information, including Personal Data, is processed at the Company&apos;s operating offices and in any other places where the parties involved in the processing are located. We ensure all international transfers adhere to adequate security safeguards.
      </p>

      <h2>Delete Your Personal Data</h2>
      <p>
        You have the right to delete or request that We assist in deleting the Personal Data that We have collected about You. You may also contact Us to request access to, correct, or delete any Personal Data that You have provided to Us.
      </p>

      <h2>Security of Your Personal Data</h2>
      <p>
        The security of Your Personal Data is important to Us, but remember that no method of transmission over the Internet, or method of electronic storage, is 100% secure. While We strive to use commercially reasonable means to protect Your Personal Data, We cannot guarantee its absolute security.
      </p>

      <h2>Children&apos;s and Minors&apos; Privacy</h2>
      <p>
        The Service is not directed to, and We do not knowingly collect Personal Information from, anyone under the age of 16.
      </p>

      <h2>Changes to this Privacy Policy</h2>
      <p>
        We may update Our Privacy Policy from time to time. We will notify You of any changes by posting the new Privacy Policy on this page and updating the &quot;Last updated&quot; date at the top of this Privacy Policy.
      </p>

      <div className="legal-contact-card">
        <h3 style={{ margin: "0 0 12px", color: "#0f172a", fontSize: 18, fontWeight: 700 }}>Contact Us</h3>
        <p style={{ margin: "0 0 12px", fontSize: 14 }}>If You have any questions about this Privacy Policy, You can contact Us:</p>
        <div style={{ display: "flex", flexDirection: "column", gap: 8, fontSize: 14 }}>
          <div style={{ display: "flex", alignItems: "center", gap: 8 }}>
            <Mail size={16} color="#64748b" />
            <a href="mailto:support@doxez.in">support@doxez.in</a>
          </div>
          <div style={{ display: "flex", alignItems: "center", gap: 8 }}>
            <Phone size={16} color="#64748b" />
            <a href="tel:+919692949500">+91 96929 49500</a>
          </div>
          <div style={{ display: "flex", alignItems: "flex-start", gap: 8 }}>
            <MapPin size={16} color="#64748b" style={{ flexShrink: 0, marginTop: 2 }} />
            <span>IIT-Bhubaneswar Research Park, Samantapuri, Bhubaneswar – 751013</span>
          </div>
        </div>
      </div>
    </LegalDocumentLayout>
  );
}
